version: '3.7'

services:
  back:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: bash enntrypoint.sh
    #  sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 config.asgi:application"
 #     sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
#    command: >
#      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    ports:
      - 5432:5432

  redis-server:
    image: "redis:alpine"
    command: redis-server
    env_file:
      - ./.env.dev

volumes:
  postgres_data:



